### ISSUE TITLE
Error message when download an album and a track in unavailable for download

### ISSUE THREAD

**Issue by nath2125** [ImAiiR/QobuzDownloaderX#132]
Hi there and love the platform btw, but I'm getting this error message when downloading a whole album and a track in the middle of it being unavailable, it skips the rest of them.
![image](https://user-images.githubusercontent.com/99367069/227948515-712eace0-8ead-4ca1-85b5-ba57745e1644.png)

**Comment by Hrenwamm** [comment]
![RUBU1](https://github.com/ImAiiR/QobuzDownloaderX/assets/50029123/2bbe510e-672f-4d79-aed6-eabdad83eaa3)
![RUBU1](https://github.com/ImAiiR/QobuzDownloaderX/assets/50029123/3982c59c-6a6e-4812-b571-d4b3d4ef4824)
![Знімок екрана (1)](https://github.com/ImAiiR/QobuzDownloaderX/assets/50029123/9cff65d7-658c-4d8d-9ae1-48d05e7d63bb)

**Comment by Hrenwamm** [comment]
[ERROR] Album Download Task ERROR. Details saved to error log.
2023-09-10 21:10:17.994 : ===================================================================
2023-09-10 21:10:17.995 : Downloading <Album> from https://play.qobuz.com/album/zbopgexlxtexc
2023-09-10 21:10:17.997 : ===================================================================

2023-09-10 21:10:18.002 : Grabbing Album info...
2023-09-10 21:10:18.082 : Album "Voyage" found. Starting Downloads...

2023-09-10 21:10:18.163 : [ERROR] Album Download Task ERROR. Details saved to error log.
Album Download Task ERROR.
System.NullReferenceException: Object reference not set to an instance of an object.
   at QobuzDownloaderX.Models.DownloadItemInfo.SetAlbumCoverArtUrls(Album qobuzAlbum)
   at QobuzDownloaderX.Models.DownloadItemInfo.SetAlbumDownloadInfo(Album qobuzAlbum)
   at QobuzDownloaderX.Shared.DownloadManager.<DownloadAlbumAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at QobuzDownloaderX.Shared.DownloadManager.<StartDownloadAlbumTaskAsync>d__37.MoveNext()

**how to deal with this?**
