### ISSUE TITLE
Failure while downloading

### ISSUE THREAD

**Issue by r2d2fenix** [ImAiiR/QobuzDownloaderX#140]
Failed to download (First Phase). Error information below.

System.NullReferenceException: Object reference not set to an instance of an object.
   at QobuzDownloaderX.QobuzDownloaderX.<downloadAlbumBG_DoWork>d__263.MoveNext()

**Comment by daqwankoenig** [comment]
Getting this error as well today

**Comment by daqwankoenig** [comment]
Track Download ERROR. Information below.

System.IO.IOException: The process cannot access the file 'C:\Users\daqwa\Downloads\qbdlx\AC_DC\Back In Black\FLAC (24bit-96kHz)\04 - Givin the Dog a Bone.flac' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at TagLib.File.LocalFileAbstraction.get_WriteStream()
   at TagLib.File.set_Mode(AccessMode value)
   at TagLib.Flac.File.Save()
   at QobuzDownloaderX.QobuzDownloaderX.<downloadAlbumBG_DoWork>d__263.MoveNext()

also o believe this is a related error 
noticed that files that have this error do not have all the metadata 
I tired running the program as admin but this does not help
