### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by Hamdan997** [ImAiiR/QobuzDownloaderX#25]
it was working yesterday 
i downloaded two or three albums 
then this error showed up 
Track Download ERROR. Information below.

System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at QobuzDownloaderX.QobuzDownloaderX.<downloadAlbumBG_DoWork>d__91.MoveNext()
![image](https://user-images.githubusercontent.com/66077190/83158789-e3fee100-a10d-11ea-9b29-f1ed567c2fd5.png)

**Comment by ImAiiR** [comment]
I can't seem to reproduce the error on my end using the same album. Try these things for me and tell me if anything works.

- Make sure your PC date & time is set correctly.
- Log out of QBDLX and log back in. If using the alternative method for logging in, get new values for token & id.
- If connected to a VPN, try switching to a new server, or disconnect entirely to see if that is the issue.
- I don't think this would do anything, but sometimes it just works, restart your computer.

If you end up getting a new error let me know what it is.

**Comment by Hamdan997** [comment]
the problem solved 
that issue caused by vpn running in background 
thanks mate
