### ISSUE TITLE
Album cover error

### ISSUE THREAD

**Issue by ciaranvisuals** [ImAiiR/QobuzDownloaderX#26]
Hi, downloads of albums keeps stopping saying the album cover file is in use. It seems to only happen on most albums when album cover quality is on max. Thanks

**Comment by ImAiiR** [comment]
Could you paste the full error it gives you? Also could you provide a link to the album(s) that give you this error?

**Comment by ciaranvisuals** [comment]
Track Download ERROR. Information below.

System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   at System.Net.Sockets.NetworkStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.Net.FixedSizeReader.StartReading()
   at System.Net.Security._SslStream.StartFrameHeader(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.StartReading(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.BeginRead(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.TlsStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.PooledStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.Net.ConnectStream.BeginReadWithoutValidation(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.Net.ConnectStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndReadAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.<>n__0(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.<ReadAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.IO.Stream.<CopyToAsyncInternal>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at QobuzDownloaderX.QobuzDownloaderX.<downloadFaveAlbumsBG_DoWork>d__89.MoveNext()

If some tracks aren't available for streaming on the album you're trying to download, try to manually download the available tracks individually.

**Comment by ciaranvisuals** [comment]
https://open.qobuz.com/album/u77kmw2ol6j0b

**Comment by ImAiiR** [comment]
Alright, it doesn't seem to be happening on my end, and the error seems to be similar to an error that was caused by a VPN, so here's a few options, let me know if any of these fix the issue for you.

- Make sure your PC date & time is set correctly.
- Log out of QBDLX and log back in. If using the alternative method for logging in, get new values for token & id.
- If connected to a VPN, try switching to a new server, or disconnect entirely to see if that is the issue.
- Check your firewall settings, as something could be blocking requests.
- I don't think this would do anything, but sometimes it just works, restart your computer.

If none of the above works, but you get a new error, or you find another fix, please let me know.

**Comment by ciaranvisuals** [comment]
Syncing the date & time seems to have solved the issue. Thanks for the prompt help 👍👍
