### ISSUE TITLE
Track Downloiad Error

### ISSUE THREAD

**Issue by Justinwang677** [ImAiiR/QobuzDownloaderX#27]
Track Download ERROR. Information below.

TagLib.CorruptFileException: FLAC stream not found at starting position.
   at TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle propertiesStyle)
   at TagLib.File.Create(String path)
   at QobuzDownloaderX.QobuzDownloaderX.<downloadTrackBG_DoWork>d__92.MoveNext()

After download, it will only download 30 seconds or a partial song

**Comment by ImAiiR** [comment]
Make sure your Qobuz subscription is still active.

**Comment by Justinwang677** [comment]
My subscription is still active but the error still shows

Studio Premier
You have access to your Qobuz Studio plan until 6/21/20.
